language: c

os:
  - osx

compiler:
  - clang

before_install:
  - "brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)"

install:
  - brew install
    protobuf
    protobuf-c
    Gsasl
    openssl
    thrift
    ccache
    snappy
    libevent
    python
    bison
  - brew outdated libyaml || brew upgrade libyaml
  - brew outdated json-c || brew upgrade json-c
  - brew outdated boost || brew upgrade boost
  - brew outdated maven || brew upgrade maven
  - brew tap brona/iproute2mac
  - brew install iproute2mac
  - sudo pip install pycrypto paramiko

before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./configure

script:
  - wget https://scan.coverity.com/download/linux64 --post-data "token=VwyU1SmtMuuwyDH5b1qLtA&project=hawqcore%2Fincubator-hawq" -O coverity_tool.tgz
  - tar zxvf coverity_tool.tgz
  - $PWD/cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j$(sysctl -n hw.ncpu)
  - tar czvf cov.tgz cov-int
  - "curl --form token=VwyU1SmtMuuwyDH5b1qLtA --form email=dev@hawq.incubator.apache.org --form file=@cov.tgz --form version=2.0.0.0 --form description=HadoopWithSql https://scan.coverity.com/builds?project=hawqcore%2Fincubator-hawq"

branches:
  except:
    - legacy
